presentation/Beadwork.Web/Controllers/PictureController.cs
using Beadwork.Web.App;
using Microsoft.AspNetCore.Mvc;

namespace Beadwork.Web.Controllers
{
    public class PictureController : Controller
    {
        private readonly PictureService pictureService;
        public PictureController(PictureService pictureService)
        {
            this.pictureService = pictureService;
        }
        public IActionResult Index(int id)
        {
            var model = pictureService.GetById(id);

            return View(model);
        }
    }
}

presentation/Beadwork.Web/Controllers/SearchController.cs
using Beadwork.Web.App;
using Microsoft.AspNetCore.Mvc;

namespace Beadwork.Web.Controllers
{
    public class SearchController : Controller
    {
        private readonly PictureService pictureService;
        public SearchController(PictureService pictureService)
        {
            this.pictureService = pictureService;
        }
        public IActionResult Index(string query)
        {
            var pictures = pictureService.GetAllByQuery(query);

            return View("Index", pictures);
        }
    }
}

presentation/Beadwork.Web/Views/Search/Index.cshtml
@using Beadwork.Web.Controllers
@using Beadwork.Web.App

@model IReadOnlyCollection<PictureModel>

@{
    ViewData["Title"] = "Результати пошуку";
}

<h1>Результати пошуку</h1>
@if (Model.Count == 0)
{
    <p>Нічого не знайдено</p>
}
else
{
    <ul>
        @foreach (var picture in Model)
        {
            <li><a href="@Url.Action("Index", "Picture", new { id = picture.Id })">@picture.Title</a></li>
        }
    </ul>
}